Use docformatter v1.6.0-rc2 to fix admonitions.
Refs:
https://github.com/PyCQA/docformatter/issues/157
https://github.com/PyCQA/docformatter/issues/127

diff --git a/.github/workflows/autofix.yaml b/.github/workflows/autofix.yaml
--- a/.github/workflows/autofix.yaml
+++ b/.github/workflows/autofix.yaml
@@ -126,8 +126,11 @@ jobs:
         run: |
           pycln --all .
       - name: Run docformatter
+        # Always ignore failing command: docformatter returns exit code 3 if it finds a file that needs to be reformatted:
+        # https://github.com/PyCQA/docformatter/issues/157#issuecomment-1402573058
+        # https://github.com/PyCQA/docformatter/pull/137/files#diff-66e28562c85a1bb96f431f2dd52bbabab914359e4b06f58eb1e18eadc01f5c06R96
         run: |
-          docformatter --recursive --in-place --wrap-summaries 88 --wrap-descriptions 88 .
+          docformatter --recursive --in-place --wrap-summaries 88 --wrap-descriptions 88 . || true
       - name: Run blacken-docs
         # blacken-docs reuses Black's ``--target-version pyXY`` parameter.
         # Ignore failing command: blacken-docs returns 1 if it finds a file that needs to be reformatted:
