Change the order of Python auto-formatting pipeline.

diff --git a/.github/workflows/autofix.yaml b/.github/workflows/autofix.yaml
--- a/.github/workflows/autofix.yaml
+++ b/.github/workflows/autofix.yaml
@@ -113,24 +113,21 @@ jobs:
       - name: Install pip
         run: |
           python -m pip install --upgrade pip
-      - name: Install isort, pycln, docformatter, blacken-docs, autopep8 and black
+      - name: Install pycln, isort, black, blacken-docs, autopep8 and docformatter
         run: >
           python -m pip install --requirement
           https://raw.githubusercontent.com/kdeldycke/workflows/main/requirements.txt
-      - name: Run isort
-        # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort
-        run: |
-          isort --profile black .
       - name: Run pycln
         # Black is not removing unused imports, as per https://github.com/psf/black/issues/86 . So we rely on pycln.
         run: |
           pycln --all .
-      - name: Run docformatter
-        # Always ignore failing command: docformatter returns exit code 3 if it finds a file that needs to be reformatted:
-        # https://github.com/PyCQA/docformatter/issues/157#issuecomment-1402573058
-        # https://github.com/PyCQA/docformatter/commit/f7d50ae
+      - name: Run isort
+        # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort
         run: |
-          docformatter --recursive --in-place --wrap-summaries 88 --wrap-descriptions 88 . || true
+          isort --profile black .
+      - name: Run Black
+        run: |
+          black ${{ needs.project-metadata.outputs.black_params }} .
       - name: Run blacken-docs
         # blacken-docs reuses Black's ``--target-version pyXY`` parameter.
         # Ignore failing command: blacken-docs returns 1 if it finds a file that needs to be reformatted:
@@ -149,9 +146,12 @@ jobs:
         #  - --aggressive is requires to force autopep8 to consider comments.
         run: |
           autopep8 --recursive --in-place --max-line-length 88 --select E501 --aggressive .
-      - name: Run Black
+      - name: Run docformatter
+        # Always ignore failing command: docformatter returns exit code 3 if it finds a file that needs to be reformatted:
+        # https://github.com/PyCQA/docformatter/issues/157#issuecomment-1402573058
+        # https://github.com/PyCQA/docformatter/commit/f7d50ae
         run: |
-          black ${{ needs.project-metadata.outputs.black_params }} .
+          docformatter --recursive --in-place --wrap-summaries 88 --wrap-descriptions 88 . || true
       - uses: peter-evans/create-pull-request@v4.2.3
         with:
           assignees: ${{ github.actor }}
