Upload Nuitka crash report as artifacts when the build fails
Refs: https://github.com/Nuitka/Nuitka/issues/3637

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -183,9 +183,21 @@ jobs:
         run: |
           uv --no-progress run --frozen -- nuitka --version
       - name: Build binary
+        id: build-binary
+        continue-on-error: true
         run: >
           uv --no-progress run --frozen -- nuitka
           --onefile --assume-yes-for-downloads --output-filename=${{ matrix.bin_name }} ${{ matrix.module_path }}
+      - name: Upload Nuitka crash report
+        uses: actions/upload-artifact@v4.6.2
+        with:
+          name: nuitka-crash-report-${{ matrix.os }}.xml
+          if-no-files-found: ignore
+          path: nuitka-crash-report.xml
+      - if: steps.build-binary.outcome == 'failure'
+        run: |
+          echo "Nuitka build failed, skipping the rest of the steps."
+          exit 1
       - name: Install exiftool - Linux
         if: runner.os == 'Linux'
         run: |
